name: ieee_event_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  #State Management
  flutter_bloc: ^8.1.2
  modular_bloc_bind: ^1.0.1
  hydrated_bloc: ^9.1.2
  
  #Navigation
  flutter_modular: ^5.0.3

  #Network,json
  dio: ^5.1.2
  equatable: ^2.0.5

  #Log
  logger: ^1.1.0

   #Firebase
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  cloud_firestore: ^4.8.0
  google_sign_in: ^6.1.0
  firebase_storage: ^11.2.5

  #Utility
  intl: ^0.18.0
  freezed_annotation: ^2.2.0
  internet_connection_checker: ^1.0.0
  easy_localization: ^3.0.2
  smooth_page_indicator: ^1.1.0
  dartz: ^0.10.1
  pretty_dio_logger: ^1.3.1
 
  #UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  freezed: ^2.3.2
  lints: ^2.1.0
  mocktail: ^0.3.0
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
